### ISSUE TITLE
Minar tolerance

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/sal-stack-nanostack-eventloop#18]
In here https://github.com/ARMmbed/sal-stack-nanostack-eventloop/blob/master/source/system_timer.cpp#L108 a periodic callback of period TIMER_SYS_TICK_PERIOD ms is posted but the tolerance is not set.

Minar have a default tolerance of 50 ms which is large considering TIMER_SYS_TICK_PERIOD is only 10 ms. Hence it would be wise to explicitly set a tolerance for this callback.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2386

**Comment by mlnx** [comment]
@SeppoTakalo could you please comment on this issue?

**Comment by SeppoTakalo** [comment]
Fixed in v1.0.7
https://github.com/ARMmbed/sal-stack-nanostack-eventloop/commit/d8998b74434905525bac1103dd6d9b73e9b09fc4
