### ISSUE TITLE
eventOS_event_timer.h Doxygen /params don't match functions

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/sal-stack-nanostack-eventloop#25]
https://github.com/ARMmbed/sal-stack-nanostack-eventloop/blob/master/nanostack-event-loop/eventOS_event_timer.h#L26
https://github.com/ARMmbed/sal-stack-nanostack-eventloop/blob/master/nanostack-event-loop/eventOS_event_timer.h#L36
https://github.com/ARMmbed/sal-stack-nanostack-eventloop/blob/master/nanostack-event-loop/eventOS_event_timer.h#L46

**Comment by kjbracey-arm** [comment]
I think my recent changes covered this - care to recheck?

**Comment by korjaa** [comment]
I should have linked those files against some commit instead of master.
https://github.com/ARMmbed/sal-stack-nanostack-eventloop/blob/16bda35ac1f32e53c1efd8b51578e67f2770ca9c/nanostack-event-loop/eventOS_event_timer.h#L26
https://github.com/ARMmbed/sal-stack-nanostack-eventloop/blob/16bda35ac1f32e53c1efd8b51578e67f2770ca9c/nanostack-event-loop/eventOS_event_timer.h#L36
https://github.com/ARMmbed/sal-stack-nanostack-eventloop/blob/16bda35ac1f32e53c1efd8b51578e67f2770ca9c/nanostack-event-loop/eventOS_event_timer.h#L46

**Comment by korjaa** [comment]
All but shortest active timer was good:
- [x] eventOS_event_timer_request()
- [x] eventOS_event_timer_cancel()
- [ ] [eventOS_event_timer_shortest_active_timer()](https://github.com/ARMmbed/sal-stack-nanostack-eventloop/blob/master/nanostack-event-loop/eventOS_event_timer.h#L209)
  - Line 209 still has ticks mentioned as a parameter

**Comment by korjaa** [comment]
Yup, fixed now.
